In [1]:
import tensorflow as tf

/Users/yoonwogud/Desktop/Git/BlueMoon/BlueMoonEnv/lib/python3.9/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(


In [2]:
## data 선언
x_data =[[1.],[2.],[3.],[4.]]
y_data =[[1.],[3.],[5.],[7.]]

In [3]:
## 평균 0, 분산 1의 파라미터의 정규분포로 부터 값을 가져옴.
# 학습을 통해 업데이트가 되어 변화되는 모델의 파라미터인 w,b를 의미한다.
W= tf.Variable(tf.random.normal((1,1), mean=0, stddev=1))  
b= tf.Variable(tf.random.normal((1,1), mean=0, stddev=1))
print("W : ", W)
print("b : ", b)

W :  <tf.Variable 'Variable:0' shape=(1, 1) dtype=float32, numpy=array([[-0.12460757]], dtype=float32)>
b :  <tf.Variable 'Variable:0' shape=(1, 1) dtype=float32, numpy=array([[-0.86865246]], dtype=float32)>


In [7]:
for j in range(len(x_data)):
    ## data * weight 작성
    WX = tf.matmul([x_data[j]], W)

    ## bias add 작성
    y_hat = tf.add(WX, b)

    ## W와 b로 예측 하기
    print("y_data: , ",y_data[j], "prediction : ", y_hat)

y_data: ,  [1.0] prediction :  tf.Tensor([[-0.99326]], shape=(1, 1), dtype=float32)
y_data: ,  [3.0] prediction :  tf.Tensor([[-1.1178676]], shape=(1, 1), dtype=float32)
y_data: ,  [5.0] prediction :  tf.Tensor([[-1.2424752]], shape=(1, 1), dtype=float32)
y_data: ,  [7.0] prediction :  tf.Tensor([[-1.3670827]], shape=(1, 1), dtype=float32)
