In [1]:
import tensorflow as tf

/Users/yoonwogud/Desktop/Git/BlueMoon/BlueMoonEnv/lib/python3.9/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(


In [2]:
## matrix 선언 하기.
matrix_A = tf.constant([[2, 2, 4],
                        [1, 1, 6],
                        [1, 3, 8] ]) # 작성
matrix_B = tf.constant([[4, 3, 3],
                        [2, 1, 6],
                        [1, 2, 8] ]) # 작성

## matrix 연산하기.
result = tf.matmul(matrix_A, matrix_B) # 작성
result2 = tf.multiply(matrix_A, matrix_B)

## 결과
print("result = {}".format(result))
print("result = {}".format(result2))
##

result = [[16 16 50]
 [12 16 57]
 [18 22 85]]
result = [[ 8  6 12]
 [ 2  1 36]
 [ 1  6 64]]
