In [3]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.datasets import make_classification, make_blobs
from sklearn.datasets import load_breast_cancer

from matplotlib.colors import ListedColormap

In [4]:
fruits = pd.read_table('./fruit_data_with_colors.txt')

In [5]:
fruits

fruit_label fruit_name     fruit_subtype  mass  width  height  color_score
0             1      apple      granny_smith   192    8.4     7.3         0.55
1             1      apple      granny_smith   180    8.0     6.8         0.59
2             1      apple      granny_smith   176    7.4     7.2         0.60
3             2   mandarin          mandarin    86    6.2     4.7         0.80
4             2   mandarin          mandarin    84    6.0     4.6         0.79
5             2   mandarin          mandarin    80    5.8     4.3         0.77
6             2   mandarin          mandarin    80    5.9     4.3         0.81
7             2   mandarin          mandarin    76    5.8     4.0         0.81
8             1      apple          braeburn   178    7.1     7.8         0.92
9             1      apple          braeburn   172    7.4     7.0         0.89
10            1      apple          braeburn   166    6.9     7.3         0.93
11            1      apple          braeburn   172    7.1     7.6         0.92
12            1      apple          braeburn   154    7.0     7.1         0.88
13            1      apple  golden_delicious   164    7.3     7.7         0.70
14            1      apple  golden_delicious   152    7.6     7.3         0.69
15            1      apple  golden_delicious   156    7.7     7.1         0.69
16            1      apple  golden_delicious   156    7.6     7.5         0.67
17            1      apple  golden_delicious   168    7.5     7.6         0.73
18            1      apple       cripps_pink   162    7.5     7.1         0.83
19            1      apple       cripps_pink   162    7.4     7.2         0.85
20            1      apple       cripps_pink   160    7.5     7.5         0.86
21            1      apple       cripps_pink   156    7.4     7.4         0.84
22            1      apple       cripps_pink   140    7.3     7.1         0.87
23            1      apple       cripps_pink   170    7.6     7.9         0.88
24            3     orange     spanish_jumbo   342    9.0     9.4         0.75
25            3     orange     spanish_jumbo   356    9.2     9.2         0.75
26            3     orange     spanish_jumbo   362    9.6     9.2         0.74
27            3     orange  selected_seconds   204    7.5     9.2         0.77
28            3     orange  selected_seconds   140    6.7     7.1         0.72
29            3     orange  selected_seconds   160    7.0     7.4         0.81
30            3     orange  selected_seconds   158    7.1     7.5         0.79
31            3     orange  selected_seconds   210    7.8     8.0         0.82
32            3     orange  selected_seconds   164    7.2     7.0         0.80
33            3     orange      turkey_navel   190    7.5     8.1         0.74
34            3     orange      turkey_navel   142    7.6     7.8         0.75
35            3     orange      turkey_navel   150    7.1     7.9         0.75
36            3     orange      turkey_navel   160    7.1     7.6         0.76
37            3     orange      turkey_navel   154    7.3     7.3         0.79
38            3     orange      turkey_navel   158    7.2     7.8         0.77
39            3     orange      turkey_navel   144    6.8     7.4         0.75
40            3     orange      turkey_navel   154    7.1     7.5         0.78
41            3     orange      turkey_navel   180    7.6     8.2         0.79
42            3     orange      turkey_navel   154    7.2     7.2         0.82
43            4      lemon    spanish_belsan   194    7.2    10.3         0.70
44            4      lemon    spanish_belsan   200    7.3    10.5         0.72
45            4      lemon    spanish_belsan   186    7.2     9.2         0.72
46            4      lemon    spanish_belsan   216    7.3    10.2         0.71
47            4      lemon    spanish_belsan   196    7.3     9.7         0.72
48            4      lemon    spanish_belsan   174    7.3    10.1         0.72
49            4      lemon           unknown   132    

In [6]:
X_fruits = fruits[['height', 'width', 'mass', 'color_score']]
Y_fruits = fruits['fruit_label']

In [7]:
Y_fruits.unique()

array([1, 2, 3, 4])

In [8]:
target_name_fruit=['apple', 'mandarin', 'orange', 'lemon']

In [9]:
#랜덤 포레스트로 분류 및 시각화
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split

In [10]:
X_train, X_test, Y_train, Y_test = train_test_split(X_fruits.values,
                                                    Y_fruits.values,
                                                    random_state=0)

In [11]:
rf_clf = RandomForestClassifier()
rf_clf.fit(X_train, Y_train)

RandomForestClassifier()

In [12]:
print(rf_clf.score(X_train, Y_train))
print(rf_clf.score(X_test, Y_test))

1.0
0.8666666666666667


## 1. bagging을 사용하여 훈련시킨 후 결과를 인쇄하기

In [13]:
from sklearn.ensemble import BaggingClassifier
from sklearn.tree import DecisionTreeClassifier

In [14]:
bag_clf = BaggingClassifier(DecisionTreeClassifier(), n_estimators=500,
                            max_samples=10, n_jobs=-1, random_state=42)
bag_clf.fit(X_train, Y_train)

BaggingClassifier(estimator=DecisionTreeClassifier(), max_samples=10,
                  n_estimators=500, n_jobs=-1, random_state=42)

In [15]:
from sklearn.svm import SVC
svc_clf = BaggingClassifier(estimator=SVC(),n_estimators=10, random_state=0)
svc_clf.fit(X_train, Y_train)

BaggingClassifier(estimator=SVC(), random_state=0)

In [16]:
print(svc_clf.score(X_train, Y_train))
print(svc_clf.score(X_test, Y_test))

0.5909090909090909
0.26666666666666666


## 2. XGboost를 사용하여 훈련시킨 후 결과를 인쇄하기

In [17]:
from xgboost import XGBClassifier

In [18]:
model = XGBClassifier()
model.fit(X_train, Y_train)

ValueError: Invalid classes inferred from unique values of `y`.  Expected: [0 1 2 3], got [1 2 3 4]

In [ ]:
Y_train

array([3, 4, 2, 1, 3, 4, 3, 3, 4, 1, 4, 3, 1, 2, 3, 1, 4, 1, 4, 1, 1, 3,
       1, 4, 4, 4, 3, 1, 1, 4, 3, 2, 1, 3, 1, 1, 1, 3, 4, 2, 1, 4, 4, 4])

In [ ]:
type(Y_train)

numpy.ndarray

In [ ]:
Y_train = np.where(Y_train==1, 0, Y_train)

In [ ]:
Y_train

array([3, 4, 2, 0, 3, 4, 3, 3, 4, 0, 4, 3, 0, 2, 3, 0, 4, 0, 4, 0, 0, 3,
       0, 4, 4, 4, 3, 0, 0, 4, 3, 2, 0, 3, 0, 0, 0, 3, 4, 2, 0, 4, 4, 4])

In [ ]:
Y_train = np.where(Y_train==2, 1, Y_train)
Y_train = np.where(Y_train==3, 2, Y_train)
Y_train = np.where(Y_train==4, 3, Y_train)

In [ ]:
from sklearn.ensemble import AdaBoostClassifier

ada_clf = AdaBoostClassifier(n_estimators=30,
    learning_rate=0.5, random_state=42)
ada_clf.fit(X_train, Y_train)

AdaBoostClassifier(learning_rate=0.5, n_estimators=30, random_state=42)

In [ ]:
from sklearn.ensemble import GradientBoostingRegressor

gbrt = GradientBoostingRegressor(max_depth=2, n_estimators=3,
                                 learning_rate=1.0, random_state=42)