In [1]:
import tensorflow as tf

In [3]:
## matrix 선언 하기.
matrix_A = tf.constant([[2, 2, 4],
                        [1, 1, 6],
                        [1, 3, 8] ]) # 작성
matrix_B = tf.constant([[4, 3, 3],
                        [2, 1, 6],
                        [1, 2, 8] ]) # 작성

## matrix 연산하기.
result = tf.matmul(matrix_A, matrix_B) # 작성
result2 = tf.multiply(matrix_A, matrix_B)

## 결과
print("result = {}".format(result))
print("result = {}".format(result2))

result = [[16 16 50]
 [12 16 57]
 [18 22 85]]
result = [[ 8  6 12]
 [ 2  1 36]
 [ 1  6 64]]
