In [12]:
import tensorflow as tf

In [13]:
## data 선언
x_data =[[1.],[2.],[3.],[4.]]
y_data =[[1.],[3.],[5.],[7.]]

In [14]:
## 평균 0, 분산 1의 파라미터의 정규분포로 부터 값을 가져옴.
# 학습을 통해 업데이트가 되어 변화되는 모델의 파라미터인 w,b를 의미한다.
W=tf.Variable(tf.random.normal((1,1),mean=0, stddev=1.0))
b=tf.Variable(tf.random.normal((1,1),mean=0, stddev=1.0))
lr=tf.constant(0.0001)
print(W)
print(b)

<tf.Variable 'Variable:0' shape=(1, 1) dtype=float32, numpy=array([[1.3358953]], dtype=float32)>
<tf.Variable 'Variable:0' shape=(1, 1) dtype=float32, numpy=array([[-2.37753]], dtype=float32)>


In [15]:
for i in range(2000):  ## 에폭
    total_error = 0

    for j in range(len(x_data)): ## 배치 1
        ## data * weight
        WX =tf.matmul([x_data[j]], W)

        ## bias add
        y_hat = tf.add(WX, b)

        ## 정답인 Y와 출력값의 error 계산
        error = tf.subtract(y_data[j], y_hat)

        ## 경사하강법으로 W와 b 업데이트.
        ## 도함수 구하기
        diff_W = tf.matmul(error, [x_data[j]]) # error * x
        diff_b = error

        ##  업데이트할 만큼 러닝레이트 곱
        diff_W = tf.multiply(lr, diff_W)
        diff_b = tf.multiply(lr, diff_b) # lr * (error)

        ## w, b 업데이트
        W = tf.add(W, diff_W) # w + lr * x * (error)
        b = tf.add(b, diff_b) # b + lr * (error)
        #######

        ## 토탈 에러.
        visual_error = tf.square(error)
        total_error = total_error + visual_error

    ## 모든 데이터에 따른 error 값
    print("epoch: ", i, "error : ", total_error/len(x_data))

epoch:  0 error :  tf.Tensor([[9.758297]], shape=(1, 1), dtype=float32)
epoch:  1 error :  tf.Tensor([[9.694455]], shape=(1, 1), dtype=float32)
epoch:  2 error :  tf.Tensor([[9.631039]], shape=(1, 1), dtype=float32)
epoch:  3 error :  tf.Tensor([[9.568045]], shape=(1, 1), dtype=float32)
epoch:  4 error :  tf.Tensor([[9.505472]], shape=(1, 1), dtype=float32)
epoch:  5 error :  tf.Tensor([[9.443315]], shape=(1, 1), dtype=float32)
epoch:  6 error :  tf.Tensor([[9.381572]], shape=(1, 1), dtype=float32)
epoch:  7 error :  tf.Tensor([[9.320238]], shape=(1, 1), dtype=float32)
epoch:  8 error :  tf.Tensor([[9.259314]], shape=(1, 1), dtype=float32)
epoch:  9 error :  tf.Tensor([[9.198793]], shape=(1, 1), dtype=float32)
epoch:  10 error :  tf.Tensor([[9.138679]], shape=(1, 1), dtype=float32)
epoch:  11 error :  tf.Tensor([[9.078963]], shape=(1, 1), dtype=float32)
epoch:  12 error :  tf.Tensor([[9.019647]], shape=(1, 1), dtype=float32)
epoch:  13 error :  tf.Tensor([[8.960724]], shape=(1, 1), dty

In [16]:
# 학습이 끝난 후에, W와 b로 예측하기

#x_data =[[1.],[2.],[3.],[4.]]
#y_data =[[1.],[3.],[5.],[7.]]

print("W : ", W) # 학습이 끝난, 최적의 error에 해당하는 weight
print("b :", b) # 학습이 끝난, 최적의 error에 해당하는 bias
print("input 3 :", tf.add(tf.multiply(9, W), b))
# print("input 5 :", tf.add(tf.multiply(5, W), b))

W :  tf.Tensor([[2.3100405]], shape=(1, 1), dtype=float32)
b : tf.Tensor([[-1.9161148]], shape=(1, 1), dtype=float32)
input 3 : tf.Tensor([[18.874249]], shape=(1, 1), dtype=float32)
