01_선형회귀

In [ ]:
from sklearn.linear_model import LinearRegression

# 특징

# 특징
x = [[10.0], [8.0], [13.0], [9.0], [11.0], [14.0],
     [6.0], [4.0], [12.0], [7.0], [5.0]]

# 종속 변수
y = [8.04, 6.95, 7.58, 8.81, 8.33, 9.96,
     7.24, 4.26, 10.84, 4.82, 5.68]

# 선형회귀 모델 생성, 학습
model =  LinearRegression()
model.fit(x,y)

print(model.coef_)  # 기울기 출력
print(model.intercept_) # 절편 출력

# 회귀식: y = 0.50009091 x + 3.0000909090909094

[0.50009091]
3.0000909090909094


In [ ]:
# 정규화
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import Ridge
from sklearn.metrics import mean_squared_error

# 학습 데이터 개수 설정
train_size = 20

# 검정 데이터 개수 설정
test_size = 12

# 학습 및 검정 데이터 특징으로 사용할 무작위 표본 추출
train_x = np.random.uniform(low=0, high=1.2, size=train_size)
test_x = np.random.uniform(low=0.1, high=1.3, size=test_size)

# 학습 및 검정 데이터 종속 변수로 사용할 데이터 정의
train_y = np.sin(train_x * 2 * np.pi) + np.random.normal(0, 0.2, train_size)
test_y = np.sin(test_x * 2 * np.pi) + np.random.normal(0, 0.2, test_size)

poly = PolynomialFeatures(6) # 6차식
print(poly)
print()

PolynomialFeatures(degree=6)



In [ ]:
# 6차식에서 학습 데이터 특징으로 학습 >> 결과를 배열로 변환
train_poly_x = poly.fit_transform(train_x.reshape(train_size, 1))
test_poly_x = poly.fit_transform(test_x.reshape(test_size, 1))

In [ ]:
# Ridge 모델 생성 >> 6차식 학습결과와 학습 데이터 종속변수로 학습
model = Ridge(alpha=1.0)
model.fit(train_poly_x, train_y)
# fit() train data 로 함
# >> 왜? 모델을 구축해야 하니깐
# >> 근데 모델구축 훈련용 데이터로만 하니깐

Ridge()

In [ ]:
# 모델 활용, 예측
train_pred_y = model.predict(train_poly_x) # y_hat : 예측한 값
test_pred_y= model.predict(test_poly_x)

In [ ]:
# 학습 데이터와 검증 데이터를 대상으로 예측한 결과
# 평균제곱오차 계산
print(mean_squared_error(train_pred_y, train_y))
print(mean_squared_error(test_pred_y, test_y))

0.17910912913338656
0.4010395645884081


로직스틱 회귀

In [ ]:
np.r_[np.random.normal(3, 1, size=50),
          np.random.normal(-1, 1, size=50)]

array([ 2.97645582,  2.14227184,  2.10810912,  3.32414066,  4.07830291,
        4.10417665,  3.47834759,  2.4351544 ,  3.36471217,  2.79045419,
        3.65695651,  3.36702633,  5.49869498,  3.07999908,  4.33347878,
        4.3458546 ,  4.05376388,  3.07116413,  2.5234621 ,  3.12533153,
        1.68174342,  3.95797042,  3.30266261,  3.46123983,  2.0992266 ,
        2.15041844,  3.69278268,  2.82238824,  2.50276642,  2.05705483,
        1.85408967,  1.53889372,  3.45320508,  3.32289634,  3.19360236,
        2.3696635 ,  4.36156082,  3.90556628,  1.79633753,  2.20734046,
        1.96849849,  2.04563168,  3.0652486 ,  1.79804652,  4.13576185,
        2.81451786,  3.07101547,  2.43633413,  2.97327404,  5.11623127,
       -0.77808589, -0.87948797, -1.92500624, -0.1854131 , -0.96454466,
       -0.37286173, -1.21448572, -0.38143799,  1.30486966, -0.27838875,
        0.04028164, -1.53883594,  0.38705516, -1.43158737, -1.46707398,
       -0.66182424, -0.31965954, -1.98437757, -2.58604511, -3.23

In [ ]:
np.r_[np.random.normal(3, 1, size=50),
          np.random.normal(-1, 1, size=50)].reshape(100, -1)

array([[ 3.25887363],
       [ 4.44520914],
       [ 3.0300852 ],
       [ 3.56391719],
       [ 2.70054305],
       [ 3.43732497],
       [ 2.80058137],
       [ 4.08912161],
       [ 3.50234906],
       [ 3.17592108],
       [ 3.25168191],
       [ 2.91115257],
       [ 0.70426204],
       [ 3.18470581],
       [ 4.56866974],
       [ 1.29768033],
       [ 1.92484632],
       [ 2.47901426],
       [ 2.03193816],
       [ 3.60479146],
       [ 4.49034687],
       [ 4.01256005],
       [ 2.11949735],
       [ 3.99846855],
       [ 2.87037833],
       [ 3.06272163],
       [ 4.38394859],
       [ 1.99211981],
       [ 2.05859477],
       [ 3.52470247],
       [ 2.63538045],
       [ 2.99087408],
       [ 1.79131809],
       [ 4.08639656],
       [ 3.32410713],
       [ 1.87771367],
       [ 1.74478235],
       [ 2.5685654 ],
       [ 1.91098703],
       [ 1.97008082],
       [ 3.18773853],
       [ 3.50110004],
       [ 2.47013063],
       [ 3.73307033],
       [ 2.26590379],
       [ 0

In [ ]:
np.random.normal(3, 1, size=50)

array([3.62360007, 3.43081578, 2.41111179, 4.14872117, 1.29179503,
       4.35071941, 4.14815339, 3.29350819, 2.32748127, 1.86806751,
       3.41639966, 3.6023769 , 2.55749084, 2.0640469 , 3.15056448,
       3.98110103, 3.97005767, 4.06045718, 1.17794661, 3.62213381,
       1.70497356, 1.5065946 , 1.41289146, 2.88921213, 3.43351556,
       3.12898568, 2.495744  , 3.56057397, 3.71908865, 3.88789295,
       3.83112507, 3.95105017, 1.84279247, 3.96486314, 2.68551355,
       3.76605778, 3.70205603, 1.07841527, 4.61402462, 0.71579787,
       2.50875913, 2.45741961, 2.59133797, 2.99141372, 5.32232445,
       2.31919823, 3.36148486, 6.29458874, 2.42411813, 2.86988195])

In [ ]:
np.ones(50)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
np.zeros(50)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
np.r_[np.ones(50), np.zeros(50)]

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
import numpy as np
from sklearn.linear_model import LogisticRegression

# 특징 데이터 생성
x_train = np.r_[np.random.normal(3, 1, size=50),
          np.random.normal(-1, 1, size=50)].reshape((100,-1))

# np.random.normal(평균, 표준편차, 난수로 만든 데이터 개수)
# >> 정규분포(평균 0, 표준편차 1)
# np.r_ : 두 배열을 수평 결합

# 종속(y값) 변수 데이터 생성
y_train = np.r_[np.ones(50), np.zeros(50)]

# 로직스틱 회귀 모델 생성 및 학습과 예측
model = LogisticRegression(solver='lbfgs')

# fit() 반드시 train data 로
model.fit(x_train, y_train)

# 예측
model.predict_proba([[0],[1],[2]])[:, 1]

array([0.08843113, 0.49507542, 0.90834104])